<a href="https://colab.research.google.com/github/ganesh-2288/batch/blob/main/lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
lst1=[1,2,3]
array1 = np.array(lst1)
array1

array([1, 2, 3])

In [ ]:
type(lst1)

list

In [ ]:
array1

array([1, 2, 3])

In [ ]:
import numpy as np
lst2=[4,5,6]
array2 = np.array(lst2)
array2

array([4, 5, 6])

In [ ]:
type(lst2)

list

In [ ]:
array2

array([4, 5, 6])